#!/bin/bash

# CASE INPUTS
# Case ID
export CASE="${CASE:-4POU}"
#export CASE="${CASE:-2FJG}"

# Protein sequences separated by ":".
# Each ":"-separated block will be treated as a different chain.
export SEQ="${SEQ:-QVQLVESGGGLVQAGGSLRLSCAASGYPHPYLHMGWFRQAPGKEREGVAAMDSGGGGTLYADSVKGRFTISRDKGKNTVYLQMDSLKPEDTATYYCAAGGYQLRDRTYGHWGQGTQVTVSS:KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMSITDCRETGSSKYPNCAYKTTQANKHIIVACEGNPYVPVHFDASV}"
#export SEQ="${SEQ:-EVQLVESGGGLVQPGGSLRLSCAASGFTISDYWIHWVRQAPGKGLEWVAGITPAGGYTYYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARFVFFLPYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSC:DIQMTQSPSSLSASVGDRVTITCRASQDVSTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSGSGTDFTLTISSLQPEDFATYYCQQSYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNR:EVVKFMDVYQRSYCHPIETLVDIFQEYPDEIEYIFKPSCVPLMRCGGCCNDEGLECVPTEESNITMQIMRIKPHQGQHIGEMSFLQHNKCECRPK:EVVKFMDVYQRSYCHPIETLVDIFQEYPDEIEYIFKPSCVPLMRCGGCCNDEGLECVPTEESNITMQIMRIKPHQGQHIGEMSFLQHNKCECRPK}"

mkdir -p "${CASE}/AF2/"

# Create FASTA file (60 chars per line)
{
    echo ">${CASE}"
    echo "${SEQ}" | fold -w 60
} > "${CASE}/AF2/${CASE}.fasta"

# Run AF2-Multimer
for h in v1 v2 v3; do
    for i in */AF2/*fasta; do
        colabfold_batch "$(pwd)/$i" "$(pwd)/${i/.fasta/.colabfold.$h}" \
            --save-recycles \
            --model-type "alphafold2_multimer_${h}" \
            --recycle-early-stop-tolerance 0 \
            --rank multimer \
            --use-dropout \
            --num-recycle 20
    done
done
